version: '3.8'
services:
  backend:
    image: victor22junio/prueba-tecnica-micronaut
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_DEFAULT_URL=jdbc:postgresql://db:5432/postgresDB?preparedStatementCacheQueries=0
      - DATASOURCE_DEFAULT_USERNAME=postgresUser
      - DATASOURCE_DEFAULT_PASSWORD=postgresPW
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: victor22junio/prueba-tecnica-front
    ports:
      - "4200:4200"

volumes:
  postgres-data:
